#!/usr/bin/ruby
require 'yaml'

DEFAULT_EXCLUDE = ['.syncc', '.git', '.*.swp']

begin
  conf = YAML.load_file('.syncc')
rescue Errno::ENOENT
  abort "** No .syncc file found in the current directory."
end

abort "** No 'remotes' found in your .syncc file." unless
  conf['remotes'].to_a.length > 0

if ARGV.length != 1
  puts "Usage: syncc <alias>"
  puts "-- Your aliases: #{conf['remotes'].keys.join(', ')}"
else
  s = conf.merge(conf['remotes'][ARGV[0]])
  abort "** No remote named '#{ARGV[0]}' in your .syncc file" unless s
  s['user'] ||= ENV['SYNCC_USER']

  sync_path = s['path']
  if s['host']
    sync_path = "#{s['host']}:#{s['path']}"
    sync_path = "#{s['user']}@#{sync_path}"
  end

  excludes = (s['exclude'].to_a + DEFAULT_EXCLUDE).
    map { |x| "--exclude=#{x}" }.join(" ")
  port = s['port'] ? "-p #{s['port']}" : ""
  exec "rsync -PSauve 'ssh #{port}' #{excludes} * #{sync_path}"
end
